# Generated by Django 2.1.5 on 2019-11-02 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(blank=True, default=None, null=True)),
                ('price_8inch', models.FloatField(blank=True, default=0, null=True)),
                ('price_10inch', models.FloatField(blank=True, default=0, null=True)),
                ('price_12inch', models.FloatField(blank=True, default=0, null=True)),
                ('description', models.TextField(blank=True, default=None, null=True)),
                ('ingredients', models.TextField(blank=True, default=None, null=True)),
                ('image1', models.ImageField(blank=True, null=True, upload_to='static/image')),
                ('image2', models.ImageField(blank=True, null=True, upload_to='static/image')),
                ('image3', models.ImageField(blank=True, null=True, upload_to='static/image')),
                ('image4', models.ImageField(blank=True, null=True, upload_to='static/image')),
                ('image5', models.ImageField(blank=True, null=True, upload_to='static/image')),
                ('image6', models.ImageField(blank=True, null=True, upload_to='static/image')),
                ('image7', models.ImageField(blank=True, null=True, upload_to='static/image')),
                ('image8', models.ImageField(blank=True, null=True, upload_to='static/image')),
                ('video', models.FileField(blank=True, null=True, upload_to='static/image')),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
    ]
