# Generated by Django 2.1.5 on 2019-11-02 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_auto_20191102_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='ingredients',
            field=models.TextField(blank=True, default='eggs,vegetable oil, milk, caster sugar, self-raising flour, baking powder, salt, chocolate, butter, fondant', null=True),
        ),
    ]
