# Generated by Django 2.1.5 on 2019-11-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0005_auto_20191103_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cake',
            name='category',
            field=models.CharField(choices=[('Muffins', 'Muffins'), ('Fondant Cakes', 'Cheesecakes'), ('Cookies', 'Cookies'), ('Cakes', 'Cakes'), ('Desserts', 'Desserts')], default='Cakes', max_length=25, verbose_name='Category'),
        ),
    ]
