# Generated by Django 2.1.5 on 2019-11-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0007_auto_20191103_0020'),
    ]

    operations = [
        migrations.AddField(
            model_name='cake',
            name='long_description',
            field=models.TextField(blank=True, default='All ingredients are irish.', null=True),
        ),
    ]
